version: '3.2'
services:
  backend:
    image: alagiz/mentor-club-web-backend:latest
    environment:
      - BACKEND_DEPLOYMENT_URL=https://artem-alagizov.com/mentor-club-backend
      - AWS_LAMBDA_CONFIRMATION_EMAIL_ARN=arn:aws:lambda:us-east-2:260654294406:function:ses
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - PUBLIC_KEY_PATH=certificates/public_key.pem
      - PRIVATE_KEY_PATH=certificates/private_key_pkcs8.pem
      - POSTGRES_URL=db:5432
      - POSTGRES_DB_NAME=postgres
      - POSTGRES_USER_NAME=postgres
    volumes:
      - /var/opt/certificates:/usr/app/certificates
    command: ["java", "-jar", "/usr/app/app.jar"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.1'
          memory: 10M
    ports:
      - 8112:8080
  db:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - /var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 150M
        reservations:
          cpus: '0.1'
          memory: 10M
    ports:
      - 8113:5432
